name = "f3-the-union-fng-slack-recheck"
account_id = "9e95873fd195c60ecc99e55f563647aa"
main = "workers/fng-slack-recheck.mjs"
compatibility_date = "2026-05-19"

[vars]
PUBLIC_SITE_ORIGIN = "https://f3theunion.com"

[triggers]
crons = [ "0 13 * * *" ]
